---
title: "자바 : 오류 처리"
excerpt: 자바에서는 어떻게 오류를 제어할 수 있는지 알아봅니다.
---

사실 대부분의 오류를 확인하는 고전적인 방법은 디버깅입니다. 디버깅은 익숙해지면 손쉽게 프로그램의 흐름을 파악하고 어디서 잘못 되었는지 파악이 가능합니다.

프로그래밍 중이라면 개발자가 알아서 처리할 수 있지만 이미 완성된 프로그램으로 릴리즈되고 사용자의 손에 넘어갔다고 가정합니다. 사용자가 프로그램을 사용하다 에러를 경험하고 작업 중이던 데이터를 잃고 프로그램이 종료된다면 매우 좋지 못한 피드백을 받게 될 것입니다. 이를 방지하고자 예외 처리라는 기술을 사용하게 됩니다.

**주의**: 버그와 예외는 다르게 생각해야 합니다. 정상적인 실행이 안 되는 프로그램은 예외 처리를 해서 넘길 것이 아니라 수정되어야 합니다.
{: .notice--warning}

## 잘못된 접근

이해를 돕기 위해 일부러 배열의 잘못된 인덱스에 접근하는 코드를 작성해봅니다.

```java
public class ExceptionTest {

    public static void main(String[] args) {
        int[] arr = {1, 2, 3};

        System.out.println(arr[3]);
    }
}
```

실행하면 아래와 같은 에러 메시지를 출력합니다.

```shell
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
        at Exception.ExceptionTest.main(ExceptionTest.java:11)
```

에러의 원인은 `arr` 배열의 크기가 3인데도 불구하고 존재하지 않는 인덱스 3에 접근했기 때문입니다.

**참고**: 배열은 인덱스의 시작이 `0`입니다. 따라서 크기가 `3`인 배열이 있다면 인덱스는 `0`, `1`, `2` 입니다.
{: .notice--info}

## 예외 처리기 `try`, `catch`

자바에서 예외를 처리하는 방법은 `try`-`catch` 문을 사용하는 것입니다.

try catch 문은 다음과 같이 작성됩니다.

```java
try {
    // 예외가 발생할 수 있는 코드
} catch (예외타입 참조변수) {
    // 예외 발생시 처리하는 코드
    // 예외 종류에 따라 여러 개 작성 가능
}
finally {
    // try-catch 블록의 코드가 끝나면 무조건 실행
    // 생략 가능
}
```

문제가 발생할 수 있는 코드를 try 블록에 작성하고 예상된 예외가 발생했다면 해당 예외 catch 블록의 코드를 실행하게 됩니다.

위에 예외 발생 코드를 try-catch 블록으로 수정해보겠습니다.

```java
public class ExceptionTest2 {

    public static void main(String[] args) {

        int[] arr = {1, 2, 3};

        try {
            System.out.println(arr[4]);
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("존재하지 않는 인덱스에 접근했습니다.");
        }

    }

}
```

catch 문의 예외 타입은 아까 실행했을 때 발생한 `ArrayIndexOutOfBoundsException`입니다. 해당 예외 타입이 발생하게 되면 지금 작성해둔 catch 문이 실행됩니다.

**주의**: 실제로 서비스하는 프로그램에서는 이런 잘못된 인덱스 접근이 일어나지 않게 해야 합니다. 이는 예외가 아닌 명백한 버그입니다.
{: .notice--warning}
